export interface AppartmentFeatures{
  chnia : boolean,
  malit : boolean,
  mizog :boolean,
  merpeset : boolean,
  memad : boolean ,
  sorgeem : boolean,
  machsan : boolean,
  gishaLnechim : boolean,
  meshopetzet : boolean,
  merohetet : boolean,
  bladiot : boolean,
  minFloor : number,
  maxFloor : number,
  minSize : number,
  maxSize : number,
  entranceDate : Date ,
  immediateEntrance : boolean,
  freeTextSearch : string
}
